version: '3.8'

services:
  auth-service:
    image: authservice
    container_name: auth-service
    build:
      context: ./back-end/auth-service/
    restart: on-failure
    networks:
      - app_network
    depends_on:
      rabbitmq:
        condition: service_healthy

  profile-service:
    image: profileservice
    container_name: profile-service
    build:
      context: ./back-end/profile-service/
    restart: on-failure
    networks:
      - app_network
    depends_on:
      rabbitmq:
        condition: service_healthy

  match-service:
    image: matchservice
    container_name: match-service
    build:
      context: ./back-end/match-service/
    restart: on-failure
    networks:
      - app_network
    depends_on:
      rabbitmq:
        condition: service_healthy

  apiGateway:
    image: apigateway
    container_name: api-gateway
    build:
      context: ./back-end/apiGateway/
    ports:
      - 7000:443
      - 6000:80
    networks:
      - app_network

  rabbitmq:
    image: rabbitmq:3-management
    hostname: rabbitmq
    container_name: rabbitmq
    ports:
      - 5672:5672
      - 15672:15672
    healthcheck:
      test: rabbitmq-diagnostics -q ping
      interval: 10s
      timeout: 20s
      retries: 2
    networks:
      - app_network
    
networks:
  app_network:
    driver: bridge